# Example Node Build
# There are several problems with this image
# DO NOT COPY
# See Dockerfile-multi for a better starting point

FROM node:latest

ENV NODE_ENV production

WORKDIR /usr/src/app

COPY package.json .
RUN npm install
USER node
COPY . .

EXPOSE 3000

CMD npm start
